swagger: '2.0'

tags:
- name: pet
  description: Everything about your Pets
  externalDocs:
    description: Find out more
    url: 'http://swagger.io'
- name: store
  description: Access to Petstore orders
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: 'http://swagger.io'
