swagger: '2.0'

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'

host: petstore.swagger.io
basePath: /v2
schemes:
- https
- http

info:
  $ref: api/info/index.yaml#/info

tags:
  $ref: api/tags/index.yaml#/tags

paths:
  $ref: api/paths/index.yaml#/paths

securityDefinitions:
  $ref: api/security/securityDefinitions.yaml#/securityDefinitions

definitions:
  # example: simple description.
  Order:
    type: object
    properties:
      id:
        type: integer
        format: int64
      petId:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int32
      shipDate:
        type: string
        format: date-time
      status:
        type: string
        description: Order Status
        enum:
        - placed
        - approved
        - delivered
      complete:
        type: boolean
        default: false
    xml:
      name: Order

  # example: Model body is the root section
  User:
    $ref: api/definitions/group_2/User.yaml

  # example: Model name is the root section
  Pet:
    $ref: api/definitions/group_2/Pet.yaml#/Pet

  # example: few Models are placed in a common file
  Category:
    $ref: api/definitions/group_1.yaml#/definitions/Category
  Tag:
    $ref: api/definitions/group_1.yaml#/definitions/Tag

  ApiResponse:
    $ref: api/definitions/ApiResponse.yaml#/definitions/ApiResponse


